CREATE LOGIN [LearnerRater]
    WITH PASSWORD = N'E2WvvS{VyCwypiutioramT5cmsFT7_&#$!~<{J_jvdy|qeye', SID = 0xCB98DB5018BFB649AC57EA6BE745A136, DEFAULT_DATABASE = [LearnerRater], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

